version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: florkafun-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: florkafun
      POSTGRES_USER: florkafun_user
      POSTGRES_PASSWORD: florkafun_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - florkafun-network

  # Adminer para gestión de base de datos
  adminer:
    image: adminer:latest
    container_name: florkafun-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - florkafun-network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: florkafun-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - florkafun-network

volumes:
  postgres-data:
  redis-data:

networks:
  florkafun-network:
    driver: bridge