version: '3'

services:
  # Frontend React
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: >
      bash -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    depends_on:
      - strapi

  # Backend Strapi
  strapi:
    image: strapi/strapi:latest
    volumes:
      - ./backend:/srv/app
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=./data.db
      - APP_KEYS=toBeModified1,toBeModified2
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - JWT_SECRET=tobemodified