name: Simple Deploy to Contabo VPS

on:
  push:
    branches: [ main, master, feat/ui-uniformity ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Contabo VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CONTABO_HOST }}
        username: ${{ secrets.CONTABO_USERNAME }}
        password: ${{ secrets.CONTABO_PASSWORD }}
        port: ${{ secrets.CONTABO_PORT }}
        script: |
          # Ir al directorio del proyecto
          cd /opt/florka-fun || exit 1
          
          # Actualizar código
          git fetch origin
          git reset --hard origin/main
          
          # Instalar certificados SSL si existen
          if [ -f "ssl/florkafun.crt" ] && [ -f "ssl/florkafun.key" ]; then
            echo "🔐 Instalando certificados SSL..."
            sudo mkdir -p /etc/ssl/certs /etc/ssl/private
            sudo cp ssl/florkafun.crt /etc/ssl/certs/florkafun.crt
            sudo cp ssl/florkafun.key /etc/ssl/private/florkafun.key
            sudo chmod 644 /etc/ssl/certs/florkafun.crt
            sudo chmod 600 /etc/ssl/private/florkafun.key
            sudo chown root:root /etc/ssl/certs/florkafun.crt
            sudo chown root:root /etc/ssl/private/florkafun.key
            echo "✅ Certificados SSL instalados"
            
            # Configurar nginx con SSL
            if [ -f "setup-nginx-cloudflare-ssl.sh" ]; then
              chmod +x setup-nginx-cloudflare-ssl.sh
              sudo bash setup-nginx-cloudflare-ssl.sh
              echo "✅ Nginx configurado con SSL"
            fi
          fi
          
          # Ejecutar script de recuperación
          chmod +x emergency-recovery.sh
          bash emergency-recovery.sh
          
          echo "✅ Deployment con SSL completado"